{{- if and (not .Values.existingSecret) (not .Values.linodeToken) }}
{{- fail "Either .Values.linodeToken or .Values.existingSecret must be set." }}
{{- end }}
{{- if and (not .Values.existingSecret) .Values.linodeToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linode-vlan-topology-exporter.fullname" . }}
  labels:
    {{- include "linode-vlan-topology-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secretKey }}: {{ .Values.linodeToken | quote }}
{{- end }}
