{{- if not .Values.vlan.name }}
{{- fail ".Values.vlan.name must be set to the VLAN label." }}
{{- end }}
{{- if not .Values.vlan.cidr }}
{{- fail ".Values.vlan.cidr must be set to the CIDR block to allocate addresses from." }}
{{- end }}
{{- if and (not .Values.existingSecret) (not .Values.linodeToken) }}
{{- fail "Either .Values.linodeToken or .Values.existingSecret must be set." }}
{{- end }}
{{- if and (not .Values.existingSecret) .Values.linodeToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lke-vlan-controller.fullname" . }}
  labels:
    {{- include "lke-vlan-controller.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.secretKey }}: {{ .Values.linodeToken | quote }}
{{- end }}
