apiVersion: v2
name: linode-vlan-topology-exporter
description: Prometheus exporter for Linode VLAN topology
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - linode
  - vlan
  - prometheus
  - exporter
sources:
  - https://github.com/ram-pi/linode-charts
maintainers:
  - name: ram-pi
