apiVersion: v1
kind: Service
metadata:
  name: {{ include "lke-node-cache-manager.fullname" . }}-metrics
  labels:
    {{- include "lke-node-cache-manager.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "lke-node-cache-manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
