# helm upgrade --install universal-lke-vlan-controller ./charts/universal-lke-vlan-controller \
# --namespace lke-vlan-controller \
# --create-namespace \
# --values examples/universal-lke-vlan-controller.values.yaml \
# --set linodeToken=<LINODE_TOKEN>

vlan:
  name: "my-private-vlan"
  cidr: "172.16.1.0/24"
  excludedIPs: [ "172.16.1.1", "172.16.1.2" ]

namespace:
  create: true

deployment:
  replicas: 2
  image:
    repository: ghcr.io/ram-pi/pylinode-vlan-attacher
    tag: "0.1.2"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

controller:
  applyChanges: true
  createNamespaceIfMissing: false
  pollIntervalSeconds: 60
  nodeSelector:
    "vlan": "enabled"
