{{- if not .Values.firewall.ids }}
{{- fail ".Values.firewall.ids must be set to at least one Linode Cloud Firewall ID." }}
{{- end }}
{{- if and (not .Values.existingSecret) (not .Values.linodeToken) }}
{{- fail "Either .Values.linodeToken or .Values.existingSecret must be set." }}
{{- end }}
{{- if and (not .Values.existingSecret) .Values.linodeToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lke-firewall-updater.fullname" . }}
  labels:
    {{- include "lke-firewall-updater.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.secretKey }}: {{ .Values.linodeToken | quote }}
{{- end }}
